### PR TITLE
Added NonManagedCopy extension method to Realm collections

### PR DESCRIPTION
**Pull request by pkizak**
This should come in handy. Simple extension methods to simplify creating non-managed copy of Realm query results or lists.

### CODE REVIEW

**Comment by sushihangover** [comment]
Thanks, looks good..

Can you add a [Test] for this in:

* [Tests.Shared.cs](https://github.com/sushihangover/Realm.Json.Extensions/blob/master/src/RealmJson.Shared.Tests/Tests.Shared.cs)

**Review by sushihangover — COMMENTED** [review]
Can you change from the spacing from spaces to tabs

**Comment by pkizak** [comment]
Should be fine now :)

**Comment by sushihangover** [comment]
@XiteZ thanks!, let me run some integration tests with the "new" Realm.Database 1.1.0 and I'll push a new Nuget today.

**Pull request merged**
